# Generated by Django 5.1.2 on 2024-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('is_librarian', models.BooleanField(default=False)),
            ],
        ),
    ]
